Readme substantially enhanced.
mrzzzrm/Deliberation2 pull request #8
Opened 2017-07-20 13:55 UTC by ephe-meral

;)

2017-07-20 14:35 UTC, mrzzzrm requested changes

2017-07-20 14:35 UTC, mrzzzrm commented on README.md
> +> Teach someone to make a game engine and they never deliver anything.
Could you be more elaborate here? I'd say appending "...not even the game engine" or similar makes things more clear.

2017-07-21 09:40 UTC, ephe-meral commented on README.md
> +> Teach someone to make a game engine and they never deliver anything.
'... except several half-made game engines' maybe?
According to https://mobile.twitter.com/mikegeig/status/403517625545670656

2017-07-21 10:57 UTC, mrzzzrm commented on README.md
> +> Teach someone to make a game engine and they never deliver anything.
That strikes me as surprisingly accurate ;)

2017-07-22 08:08 UTC, merged